### ISSUE TITLE
主题使用Akina时启用插件会跳转404

### ISSUE THREAD

**Issue by lixinzai** [NicoNicooooo/GoTop#1]

**Comment by MisakaTAT** [comment]
Hello，感谢你的反馈，我在使用Akina（v3.4.5）测试的时候未发现启用插件跳转404的问题，但是有启用插件不生效的问题，已经修复了，请使用RELEASE v2.0.1版本再次尝试
![image](https://user-images.githubusercontent.com/32693466/129476116-7a9084a3-ade5-4ac6-93c6-61e9fc6857fa.png)
